/* Astra Coach v4.3.1 — complete gym-first FIX → STRENGTHEN → BUILD data bundle. */
'use strict';
window.ASTRA_DATA={
imageBase:'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/',
phases:[
{name:'Foundation',weeks:'Weeks 1–4',title:'Move better. Build immediately.',desc:'Gym-first. Each session begins with a short mobility/control block for global stiffness, hips/adductors, trunk and shoulder/neck comfort, then supported strength and real hypertrophy work.',sets:2,effort:'Easy–moderate · leave 3–4 reps',cardio:'15–20 min Zone 2 · 2×/week',gate:'Progress when technique is steady and symptoms return near baseline by the next day.'},
{name:'Build strength',weeks:'Weeks 5–8',title:'Load the system.',desc:'Three gym sessions weekly. Main lifts move toward 3 sets. Back extensions, hip hinges and pressing progress by range and reps before load.',sets:3,effort:'Moderate · leave 2–3 reps',cardio:'20–30 min Zone 2 · 2×/week',gate:'Two comfortable weeks before increasing another variable.'},
{name:'Muscle growth',weeks:'Weeks 9–16',title:'Hypertrophy leads.',desc:'Corrective work stays short while chest, back, legs, shoulders and arms receive progressive gym volume. Pressing moves toward lower-incline or flat neutral-grip dumbbells if the shoulder remains comfortable.',sets:3,effort:'Challenging · leave ~2 reps',cardio:'25–35 min · 2×/week',gate:'Improving lifts, steady weight gain and manageable symptoms matter more than the calendar.'},
{name:'Build & perform',weeks:'Weeks 17–24',title:'Bigger. Stronger. Better engine.',desc:'Continue progressive hypertrophy and back/hip capacity. A fourth set on selected main lifts is optional when recovery is good. Barbell bench is optional and never required.',sets:4,effort:'Controlled · leave 1–3 reps',cardio:'30–40 min · 2×/week',gate:'Repeat while progress and recovery remain good.'}
],
workouts:{
A:{name:'Gym A · Push + legs',focus:'MOVE → chest · quads · back · trunk',minutes:'65–80',image:'Dumbbell_Bench_Press/0.jpg',ids:['breath','adductor','hipswitch','dbpress','legpress','row','backext','latraise','dead']},
B:{name:'Gym B · Pull + posterior',focus:'MOVE → lats · hamstrings · glutes · chest',minutes:'65–80',image:'Dumbbell_Incline_Row/1.jpg',ids:['cat','bird','latpull','rdl','machinepress','curlLeg','hipthrust','curl','pallof']},
C:{name:'Gym C · Full-body builder',focus:'MOVE → chest · legs · back · shoulders · arms',minutes:'70–85',image:'Leg_Press/0.jpg',ids:['breath','adductor','dbpress','hacksquat','cablerow','backext','latraise','triceps','curl','carry']}
},
exercises:{
breath:{name:'90/90 breathing reset',image:'Dead_Bug',kind:'MOVE',muscles:'Ribs · trunk · relaxation',equipment:'Wall or bench',min:4,max:5,rest:20,unit:'slow breaths',load:'Bodyweight',fixed:1,steps:['Lie on your back with feet supported and hips/knees near 90°.','Exhale slowly until ribs soften down.','Inhale quietly into your sides and back.','Keep jaw, neck and lower back relaxed.'],cue:'This is a reset, not a hard ab exercise.',easier:'Use a comfortable foot height.',avoid:'Forcing your lower back flat or straining your neck.'},
adductor:{name:'Adductor rock-back',image:'Groiners',kind:'MOVE',muscles:'Inner thighs · hips',equipment:'Mat',min:6,max:8,rest:20,unit:'reps / side',load:'Bodyweight',fixed:1,steps:['Start on hands and knees and extend one leg out to the side.','Keep your spine comfortable.','Rock your hips backward slowly until you feel a mild inner-thigh stretch.','Return and repeat, then switch sides.'],cue:'Gentle movement for tight inner thighs.',easier:'Keep the side leg closer.',avoid:'Pinching, numbness or aggressive end-range stretching.'},
hipswitch:{name:'90/90 hip switches',image:'90_90_Hamstring',kind:'MOVE',muscles:'Hip rotation',equipment:'Mat',min:5,max:8,rest:20,unit:'reps / side',load:'Bodyweight',fixed:1,steps:['Sit with knees bent and feet wider than your hips.','Rotate both knees gently side to side.','Use your hands behind you if needed.','Move only through the range you can control.'],cue:'Give the tighter hip time; do not force symmetry.',easier:'Use hand support and smaller range.',avoid:'Forcing either knee to the floor or creating hip pinching.'},
cat:{name:'Cat–camel',image:'Cat_Stretch',kind:'MOVE',muscles:'Spine · upper back',equipment:'Mat',min:6,max:8,rest:20,unit:'reps',load:'Bodyweight',fixed:1,steps:['Start on hands and knees.','Slowly round your spine while exhaling.','Return through neutral into a small comfortable arch.','Move segment by segment without chasing a crack.'],cue:'Motion without forcing correction.',easier:'Use a smaller range.',avoid:'Repeatedly cranking the spine to make it pop.'},
bird:{name:'Bird dog',image:'./assets/bird-dog.svg',kind:'STRENGTHEN',muscles:'Trunk · glutes · spinal endurance',equipment:'Mat',min:5,max:8,rest:40,unit:'reps / side',load:'Bodyweight',core:true,illustration:true,steps:['Start on hands and knees.','Brace lightly.','Reach one leg back and opposite arm forward.','Keep hips level; hold about 3 seconds.','Return slowly and alternate.'],cue:'Equal work both sides. Reach long, not high.',easier:'Move only one limb at a time.',avoid:'Twisting your pelvis or loading a painful shoulder.'},
dbpress:{name:'Neutral-grip dumbbell bench press',image:'Dumbbell_Bench_Press',kind:'BUILD',muscles:'Chest · triceps · front delts',equipment:'Adjustable bench + dumbbells',min:8,max:12,rest:120,unit:'reps',load:'Per dumbbell (kg)',main:true,steps:['Start on a low incline around 15–30°.','Hold dumbbells with palms facing each other or slightly angled.','Keep elbows roughly 30–45° from your torso.','Lower through a comfortable shoulder range.','Press smoothly without shrugging.'],cue:'Build your chest with a shoulder-friendly setup.',easier:'Use a higher incline, lighter dumbbells or machine press.',avoid:'Sharp shoulder pain, deep painful stretch or grinding reps.'},
machinepress:{name:'Machine chest press',image:'Leverage_Chest_Press',kind:'BUILD',muscles:'Chest · triceps · shoulders',equipment:'Chest press machine',min:10,max:15,rest:90,unit:'reps',load:'Machine weight (kg)',main:true,steps:['Adjust seat so handles are around mid-chest.','Use a comfortable grip.','Keep torso supported.','Press smoothly and return under control.'],cue:'Stable machine, hard-working chest.',easier:'Reduce load or range.',avoid:'A setup that forces the shoulders high or far behind you.'},
legpress:{name:'Leg press',image:'Leg_Press',kind:'BUILD',muscles:'Quads · glutes',equipment:'Leg press machine',min:8,max:12,rest:120,unit:'reps',load:'Machine load (kg)',main:true,steps:['Place feet around shoulder width.','Keep pelvis/back supported against the pad.','Lower until a comfortable depth without pelvic rolling.','Drive through the whole foot.'],cue:'Load the legs while the machine supports your trunk.',easier:'Use less depth and lighter load.',avoid:'Butt lifting from the pad or knees collapsing inward.'},
hacksquat:{name:'Hack squat / supported squat',image:'Hack_Squat',kind:'BUILD',muscles:'Quads · glutes',equipment:'Hack squat machine',min:8,max:12,rest:120,unit:'reps',load:'Machine load (kg)',main:true,steps:['Set shoulders and back firmly against the pads.','Use a comfortable foot position.','Descend under control.','Drive through the platform to stand.'],cue:'Supported leg loading is exactly why we use the gym.',easier:'Use leg press if hack squat is unavailable.',avoid:'Forcing depth or bouncing.'},
row:{name:'Chest-supported dumbbell row',image:'Dumbbell_Incline_Row',kind:'BUILD',muscles:'Mid-back · lats · biceps',equipment:'Incline bench + dumbbells',min:8,max:12,rest:90,unit:'reps',load:'Per dumbbell (kg)',main:true,steps:['Lie chest-down on an incline bench.','Let dumbbells hang naturally.','Pull elbows toward your hips without shrugging.','Pause and lower slowly.'],cue:'Build the upper back without feeding neck tension.',easier:'Use lighter dumbbells.',avoid:'Shrugging toward the ears or craning the neck.'},
cablerow:{name:'Seated cable row',image:'Seated_Cable_Rows',kind:'BUILD',muscles:'Lats · mid-back · biceps',equipment:'Cable row machine',min:10,max:15,rest:90,unit:'reps',load:'Stack weight (kg)',main:true,steps:['Sit tall with feet supported.','Start with arms long and ribs controlled.','Pull toward lower ribs.','Pause, then return without collapsing forward.'],cue:'Quiet neck and torso.',easier:'Reduce stack weight.',avoid:'Rocking aggressively or shrugging.'},
latpull:{name:'Neutral-grip lat pulldown',image:'Close-Grip_Front_Lat_Pulldown',kind:'BUILD',muscles:'Lats · upper back · biceps',equipment:'Lat pulldown machine',min:8,max:12,rest:90,unit:'reps',load:'Stack weight (kg)',main:true,steps:['Choose a neutral/comfortable handle.','Secure thighs and sit nearly upright.','Drive elbows down toward your sides.','Return slowly until arms are long.'],cue:'Elbows down, shoulders away from ears.',easier:'Use a lighter stack.',avoid:'Behind-neck pulling or neck shrugging.'},
rdl:{name:'Dumbbell Romanian deadlift',image:'Dumbbell_Stiff_Leg_Deadlift',kind:'STRENGTHEN + BUILD',muscles:'Hamstrings · glutes · spinal erectors',equipment:'Dumbbells',min:8,max:10,rest:120,unit:'reps',load:'Per dumbbell (kg)',main:true,steps:['Hold dumbbells close to thighs.','Keep knees softly bent and brace.','Push hips backward while keeping a comfortable spine.','Stop when hamstrings are loaded.','Drive hips forward to stand.'],cue:'Teach hips and back to tolerate load together.',easier:'Shorten range and start very light.',avoid:'Rounding to chase depth or max-effort loading early.'},
backext:{name:'45° back extension / Roman chair',image:'Hyperextensions_Back_Extensions',kind:'STRENGTHEN',muscles:'Spinal erectors · glutes · hamstrings',equipment:'45° back-extension bench / Roman chair',min:8,max:12,rest:75,unit:'reps',load:'Added weight (kg)',main:true,steps:['Set the pad just below your hip crease.','Start bodyweight with arms across chest.','Hinge forward through a short comfortable range.','Return using glutes, hamstrings and back extensors until straight.','Stop at neutral.'],cue:'Range → reps → load. Strengthen the lower back instead of endlessly cracking it.',easier:'Use a shorter range and 2 sets.',avoid:'Swinging, hyperextending or adding plates too soon.'},
curlLeg:{name:'Hamstring curl machine',image:'Lying_Leg_Curls',kind:'BUILD',muscles:'Hamstrings',equipment:'Seated or lying leg curl',min:10,max:15,rest:75,unit:'reps',load:'Machine weight (kg)',steps:['Align machine pivot with your knee.','Keep hips supported.','Curl through a comfortable range.','Lower slowly.'],cue:'Direct hamstring work with little back demand.',easier:'Use a lighter setting.',avoid:'Arching hard to finish reps.'},
hipthrust:{name:'Hip thrust machine / bench',image:'Barbell_Hip_Thrust',kind:'BUILD',muscles:'Glutes · hamstrings',equipment:'Hip thrust machine or padded bench',min:8,max:12,rest:90,unit:'reps',load:'Total load (kg)',steps:['Position yourself securely.','Plant feet so shins are near vertical at the top.','Brace and drive hips upward with glutes.','Finish with ribs controlled.','Lower slowly.'],cue:'Strong glutes support the whole hip/trunk system.',easier:'Use unloaded machine or glute bridge.',avoid:'Turning lockout into a huge low-back arch.'},
latraise:{name:'Cable / dumbbell lateral raise',image:'Side_Lateral_Raise',kind:'BUILD',muscles:'Side delts',equipment:'Cable or light dumbbells',min:12,max:20,rest:60,unit:'reps',load:'Per side (kg)',steps:['Stand tall with light weight.','Raise arms in a comfortable plane.','Keep neck relaxed.','Lower slowly.'],cue:'Build shoulders without feeding neck/upper-trap tension.',easier:'Use very light cable load and smaller range.',avoid:'Shrugging or painful overhead range.'},
triceps:{name:'Cable triceps pressdown',image:'Triceps_Pushdown',kind:'BUILD',muscles:'Triceps',equipment:'Cable stack',min:10,max:15,rest:60,unit:'reps',load:'Stack weight (kg)',steps:['Stand comfortably with elbows near your sides.','Press the handle down by straightening elbows.','Pause briefly.','Return under control.'],cue:'Keep shoulders and neck quiet.',easier:'Use lighter load.',avoid:'Leaning and shrugging.'},
curl:{name:'Dumbbell / cable curl',image:'Dumbbell_Bicep_Curl',kind:'BUILD',muscles:'Biceps · forearms',equipment:'Dumbbells or cable',min:10,max:15,rest:60,unit:'reps',load:'Per dumbbell (kg)',steps:['Keep upper arms near your sides.','Curl without swinging.','Squeeze briefly.','Lower slowly.'],cue:'Arms work; back stays quiet.',easier:'Sit on a supported bench.',avoid:'Leaning back or shrugging.'},
pallof:{name:'Pallof press',image:'Pallof_Press',kind:'STRENGTHEN',muscles:'Obliques · anti-rotation trunk',equipment:'Cable or resistance band',min:8,max:12,rest:45,unit:'reps / side',load:'Stack weight (kg)',core:true,steps:['Stand sideways to a cable at chest height.','Hold handle at chest and step out lightly.','Brace and press hands straight forward.','Resist rotation, return, then match the other side.'],cue:'Equal sets both sides; train control rather than forcing symmetry.',easier:'Move closer to the stack.',avoid:'Twisting, breath-holding or heavy load.'},
carry:{name:'Farmer carry',image:'Farmers_Walk',kind:'STRENGTHEN + ENGINE',muscles:'Grip · trunk · shoulders · hips',equipment:'Two dumbbells or kettlebells',min:30,max:45,rest:60,unit:'seconds',load:'Per hand (kg)',steps:['Hold equal weights at your sides.','Stand tall without forcing your shoulders level.','Walk slowly with controlled steps.','Breathe normally and turn carefully.'],cue:'Learn to carry load without constant correction.',easier:'Use lighter equal weights.',avoid:'One-sided heavy carries for now or shrugging into neck tension.'},
dead:{name:'Dead bug heel tap',image:'Dead_Bug',kind:'STRENGTHEN',muscles:'Abdominals · trunk control',equipment:'Mat',min:5,max:8,rest:40,unit:'reps / side',load:'Bodyweight',core:true,steps:['Lie on your back with knees around 90°.','Exhale and gently brace.','Lower one heel toward the floor through a small range.','Return and alternate.'],cue:'Start with heel taps only.',easier:'Keep arms down and make the movement smaller.',avoid:'Extending far enough that your lower back becomes sore or arches.'}
},
foods:[
{id:'whey',name:'Whey protein',emoji:'🥤',unit:'serving',base:1,portion:'1 label serving · example',p:24,c:3,f:1.5,k:120},
{id:'chicken',name:'Chicken breast',emoji:'🍗',unit:'g',base:100,portion:'100 g · cooked, skinless',p:31,c:0,f:3.6,k:165},
{id:'egg',name:'Egg',emoji:'🥚',unit:'egg',base:1,portion:'1 large egg',p:6.3,c:.4,f:4.8,k:72},
{id:'yogurt',name:'Greek yogurt',emoji:'🥣',unit:'g',base:170,portion:'170 g · plain, nonfat',p:17,c:6,f:0,k:100},
{id:'milk',name:'Milk',emoji:'🥛',unit:'ml',base:250,portion:'250 ml · whole milk',p:8,c:12,f:8,k:150},
{id:'rice',name:'White rice',emoji:'🍚',unit:'g',base:100,portion:'100 g · cooked',p:2.7,c:28,f:.3,k:130},
{id:'tofu',name:'Firm tofu',emoji:'🧈',unit:'g',base:100,portion:'100 g · check package',p:12,c:2,f:7,k:120},
{id:'tuna',name:'Tuna in water',emoji:'🐟',unit:'g',base:100,portion:'100 g · drained',p:25,c:0,f:1,k:116}
]
};
