/* Exercise images: Free Exercise DB (Unlicense). Coaching cues are adapted for a conservative return to training. */
'use strict';
window.ASTRA_DATA = {
  imageBase: 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/',
  phases: [
    {name:'Foundation', weeks:'Weeks 1–4', title:'Build your base.', desc:'Start with controlled, comfortable movement. Two strength sessions in your first week is enough; build toward three non-consecutive days.', sets:2, effort:'Easy to moderate · leave 3–4 reps', cardio:'10–20 minutes, twice a week', gate:'Repeat the phase until your technique is steady and symptoms return to baseline by the next day.'},
    {name:'Build strength', weeks:'Weeks 5–8', title:'Make consistency stronger.', desc:'Keep three full-body sessions on non-consecutive days. Add repetitions first, then the smallest available weight increase.', sets:3, effort:'Moderate · leave 2–3 reps', cardio:'20–30 minutes, twice a week', gate:'Move forward only after two comfortable weeks. Do not raise weight, sets and cardio duration together.'},
    {name:'Muscle growth', weeks:'Weeks 9–16', title:'Give muscle room to grow.', desc:'Keep three full-body sessions. Earn the top of each rep range with controlled technique. Every fourth week, reduce sets by about a third if fatigue is building.', sets:3, effort:'Challenging · leave 2 reps', cardio:'25–35 minutes, twice a week', gate:'Steady weight gain, improving lifts, and manageable next-day symptoms matter more than the calendar.'},
    {name:'Keep building', weeks:'Weeks 17–24', title:'Stronger for the long run.', desc:'Continue three full-body sessions. An extra set on the main squat, push and pull is optional when recovery is good. No need to test maximal lifts.', sets:4, effort:'Controlled · leave 1–3 reps', cardio:'30–40 minutes, twice a week', gate:'Repeat this phase or return to a lower-volume phase. Tracking continues after week 24; there is no expiry.'}
  ],
  workouts: {
    A:{name:'Core + full body', focus:'Back resilience · push · pull', minutes:'40–55', image:'./assets/bird-dog.svg', ids:['cat','bird','bridge','squat','push','row','dead','side']},
    B:{name:'Strength foundations', focus:'Legs · upper body · trunk control', minutes:'40–55', image:'Goblet_Squat/0.jpg', ids:['cat','squat','row','push','curlLeg','bridge','dead','hip']},
    C:{name:'Full-body builder', focus:'Muscle · balanced strength', minutes:'45–60', image:'Dumbbell_Incline_Row/1.jpg', ids:['cat','squat','push','row','bridge','curl','bird','hip']}
  },
  exercises: {
    cat:{name:'Cat–camel', image:'Cat_Stretch', kind:'Mobility', muscles:'Spinal movement', equipment:'Mat', min:6,max:8,rest:30,unit:'reps',load:'Bodyweight', fixed:1, steps:['Start on hands and knees, with your hands under your shoulders.','Gently round your back as you breathe out.','Ease back through neutral into a small, comfortable arch.','Move slowly between positions. Do not force an end range.'], cue:'Gentle motion, not a deep stretch.', easier:'Use a smaller range. Stop if the movement aggravates your symptoms.', avoid:'Forcing your neck or pushing through sharp, radiating pain.'},
    bird:{name:'Bird dog', image:'./assets/bird-dog.svg', kind:'Core', muscles:'Trunk · glutes · back endurance', equipment:'Mat',min:5,max:8,rest:45,unit:'reps / side',load:'Bodyweight',core:true,illustration:true,steps:['Set up on hands and knees with your gaze toward the floor.','Gently brace, then reach one leg behind you and the opposite arm forward.','Keep your hips level. Reach long, not high; hold about three seconds.','Return slowly. Repeat on the other side, keeping equal repetitions.'],cue:'Imagine a glass of water balanced on your lower back.',easier:'Slide one foot back along the floor. Add the opposite arm only when your trunk stays still.',avoid:'Twisting your pelvis, lifting too high, or loading a painful shoulder.'},
    bridge:{name:'Glute bridge',image:'Butt_Lift_Bridge',kind:'Strength',muscles:'Glutes · hamstrings',equipment:'Mat; optional light weight',min:10,max:15,rest:60,unit:'reps',load:'Added weight (kg)',steps:['Lie on your back, knees bent, with both feet planted hip-width apart.','Exhale and gently brace before lifting.','Press through both feet and lift with your glutes until shoulders, hips and knees align.','Pause for two seconds, then lower slowly.'],cue:'Stop at hip extension—not a bigger low-back arch.',easier:'Lift less high, or use short comfortable holds. Start without added weight.',avoid:'Pushing through low-back pain or shifting most of your weight to one side.'},
    squat:{name:'Goblet squat',image:'Goblet_Squat',kind:'Strength',muscles:'Quads · glutes',equipment:'Dumbbell or kettlebell; optional chair',min:8,max:12,rest:90,unit:'reps',load:'Total held weight (kg)',main:true,steps:['Hold one light weight close to your chest. Start bodyweight if needed.','Stand with a comfortable stance and gently brace.','Bend your hips and knees together. Let your knees follow your toes.','Stop at a comfortable depth and stand through the whole foot.'],cue:'Use a chair behind you as a depth target. Do not chase the depth in the photo.',easier:'Sit-to-stand from a stable chair without weight. Use light hand support when needed.',avoid:'Losing balance, collapsing into painful depth, or grinding through repetitions.'},
    push:{name:'Incline push-up',image:'Incline_Push-Up',kind:'Strength',muscles:'Chest · triceps · shoulders',equipment:'Stable bench or counter',min:8,max:12,rest:90,unit:'reps',load:'Bodyweight',main:true,steps:['Place your hands on a sturdy counter or bench that cannot slide.','Step back until your head, ribs and hips form one line.','Lower your chest slowly, keeping elbows roughly 30–45 degrees from your body.','Press away without shrugging. Breathe out as you rise.'],cue:'Choose a height that keeps the shoulder comfortable. Higher is easier.',easier:'Use a wall or higher counter. Stop pressing if your shoulder pinches.',avoid:'Deep painful range, flared elbows, sagging hips or unstable furniture.'},
    row:{name:'Chest-supported row',image:'Dumbbell_Incline_Row',kind:'Strength',muscles:'Mid-back · lats · biceps',equipment:'Incline bench + dumbbells',min:10,max:15,rest:90,unit:'reps',load:'Per dumbbell (kg)',main:true,steps:['Set an incline bench at a comfortable angle and support your chest on it.','Let both dumbbells hang with palms facing each other.','Pull elbows toward your hips without lifting your chest off the pad.','Pause briefly, then lower under control.'],cue:'Relax your neck. Move the elbows rather than jerking the weights.',easier:'Use lighter dumbbells. A securely anchored band row is an alternative; log it separately in your notes.',avoid:'Shrugging, craning the neck or arching to finish the repetition.'},
    dead:{name:'Dead bug',image:'Dead_Bug',kind:'Core',muscles:'Abdominals · trunk control',equipment:'Mat',min:6,max:10,rest:45,unit:'reps / side',load:'Bodyweight',core:true,steps:['Lie on your back with your arms pointing up and knees bent about 90 degrees.','Exhale and gently brace; keep your trunk position comfortable and steady.','Lower one heel toward the floor. Extend the leg farther only when you can control it.','Return slowly and alternate, completing the same number on each side.'],cue:'The photos show the longer-leg version. Begin with heel taps.',easier:'Keep your arms down and use a shorter leg movement. Breathe normally between repetitions.',avoid:'Arching your lower back as the leg extends, breath-holding or rushing.'},
    side:{name:'Side plank',image:'Side_Bridge',kind:'Core',muscles:'Side trunk · glutes',equipment:'Mat',min:15,max:30,rest:45,unit:'seconds / side',load:'Bodyweight',core:true,steps:['Lie on your side with your elbow directly below your shoulder.','Begin with bent knees; the photos show the harder straight-leg version.','Lift your hips to make a line from shoulder to knee or ankle.','Hold while breathing, then lower. Match the time on both sides.'],cue:'Start from the knees. Stop immediately if the shoulder pinches.',easier:'Use 10-second holds from bent knees. Replace with dead bugs if the shoulder is uncomfortable.',avoid:'Rolling forward, holding your breath, or pushing through shoulder pain.'},
    curlLeg:{name:'Lying hamstring curl',image:'Lying_Leg_Curls',kind:'Strength',muscles:'Hamstrings',equipment:'Leg curl machine',min:10,max:15,rest:75,unit:'reps',load:'Machine weight (kg)',steps:['Adjust the machine so its knee pivot matches your knee and the pad sits above your heels.','Keep your hips supported against the bench.','Curl your heels toward your glutes through a comfortable range.','Lower slowly without letting the weight stack crash.'],cue:'Your knees bend; your lower back does not need to help.',easier:'Use a very light setting or substitute an unweighted glute bridge.',avoid:'Lifting your hips, arching hard or forcing a cramped range.'},
    curl:{name:'Dumbbell biceps curl',image:'Dumbbell_Bicep_Curl',kind:'Strength',muscles:'Biceps · forearms',equipment:'Two dumbbells',min:10,max:15,rest:60,unit:'reps',load:'Per dumbbell (kg)',steps:['Stand comfortably with one dumbbell in each hand and arms by your sides.','Keep your upper arms close to your body.','Bend both elbows to lift the weights without swinging.','Lower slowly to a comfortable straight-arm position.'],cue:'Use a weight your elbows can move without your back joining in.',easier:'Use lighter weights or sit on a supported bench.',avoid:'Leaning back, swinging or cranking your wrists.'},
    hip:{name:'Kneeling hip-flexor stretch',image:'Kneeling_Hip_Flexor',kind:'Mobility',muscles:'Front of hip',equipment:'Mat or knee cushion',min:20,max:30,rest:30,unit:'seconds / side',load:'Bodyweight',fixed:1,steps:['Kneel on a cushion with your other foot planted in front.','Gently squeeze the glute on the kneeling side and keep ribs over your pelvis.','Shift forward slightly until you feel a mild stretch at the front of the hip.','Breathe, ease out, and switch sides.'],cue:'A small movement is enough. Do not turn it into a low-back arch.',easier:'Use extra knee padding and a hand on a wall for balance.',avoid:'Deep lunging, forcing the right hip or stretching into pinching pain.'}
  },
  foods:[
    {id:'whey',name:'Whey protein',emoji:'🥤',unit:'serving',base:1,portion:'1 label serving · example',p:24,c:3,f:1.5,k:120},
    {id:'chicken',name:'Chicken breast',emoji:'🍗',unit:'g',base:100,portion:'100 g · cooked, skinless',p:31,c:0,f:3.6,k:165},
    {id:'egg',name:'Egg',emoji:'🥚',unit:'egg',base:1,portion:'1 large egg',p:6.3,c:.4,f:4.8,k:72},
    {id:'yogurt',name:'Greek yogurt',emoji:'🥣',unit:'g',base:170,portion:'170 g · plain, nonfat',p:17,c:6,f:0,k:100},
    {id:'milk',name:'Milk',emoji:'🥛',unit:'ml',base:250,portion:'250 ml · whole milk',p:8,c:12,f:8,k:150},
    {id:'rice',name:'White rice',emoji:'🍚',unit:'g',base:100,portion:'100 g · cooked',p:2.7,c:28,f:.3,k:130},
    {id:'tofu',name:'Firm tofu',emoji:'🧈',unit:'g',base:100,portion:'100 g · check package',p:12,c:2,f:7,k:120},
    {id:'tuna',name:'Tuna in water',emoji:'🐟',unit:'g',base:100,portion:'100 g · drained',p:25,c:0,f:1,k:116}
  ]
};
